exports.list = [
'Bebo para olvidar _____.',
'________: Bueno hasta la ultima gota.',
'¿Qué es ese sonido?',
'¿A qué huele?',
'Durante el sexo, me gusta pensar en _____.',
'La medicina alternativa ahora usa las propiedades curativas de _____.',
'Por culpa de un error de marketing El Corte Ingles ha dejado de vender ____.',
'¿Por qué estoy pegajoso?',
'Hoy el tio de Bricomania construirá _____.',
'¿Qué me traje de Marruecos?',
'¿Qué ayuda a Obama a relajarse?',
'_________. ¡Chócala!',
'Durante el comunmente infravalorado Período Marrón de Picasso, hizo cientos de pinturas de ____.',
'It\'s a trap!',
'¿Qué es lo que mas le gusta a Aznar?',
'¡A que no puedes comer sólo uno?',
'La guerra sirve para ____.',
'¿Qué es lo que no te gustaria encontrar en un plato de comida china?',
'¿Cuál es el proximo juguete de HappyMeal?',
'¿Este año, en vez de carbón, Papa Noel traerá ____ a los niños malos.',
'¿Cómo mantengo estable mi relación de pareja?',
'Cuando sea Presidente, crearé el ministerio de _____.',
'¿Cuál es mi poder secreto?',
'EE.UU. ha empezado a enviar _____ a los niños de Afghanistan.',
'Ojalá no hubiese perdido el manual de ______.',
'¿Por qué no puedo dormir por las noches?',
'Cuando esté en la cárcel, meteré ______ de contrabando.',
'¿Que toma Vin Diesel para cenar?',
'El paraíso está lleno de _______.',
'¿Qué es lo que hay que hacer para llevarte a la cama?',
'Cuando sea millonario, levantaré una estatua de 20 metros en conmemoración de ______.',
'¿Qué encontraría tu abuela perturbador pero extrañamente encantador?',
'En la nueva película original de Disney Channel, Hannah Montana se enfrentara por primera vez con _______.',
'¿Cuál es el vicio secreto de Batman?',
'¿Qué me llevaría en un viaje al pasado para convencer a la gente de que soy un poderoso mago?',
'¿Cuál es mi anti-droga?',
'La Liga de Fútbol ha prohibido ________ por dar a los jugadores una ventaja injusta.',
'¿______? ¡Hay una aplicación para eso!',
'¿Qué me produce gases incontrolados?',
'¿Qué es lo más crujiente?',
'¿A qué huelen las personas mayores?',
'_______: probado en niños, aprobado por las madres.',
'¿Qué mejora con los años?',
'Lo siento, acabo de _____.',
'A los blancos les gusta ________.',
'La vida era difícil para los cavernicolas antes de ________.',
'¿Quién ha robado las galletas del tarro de las galletas?',
'¿Qué es lo más emo?',
'Antes de matarle, Señor Bond, me gustaria enseñarle ________.',
'La excursión al campo fue completamente arruinada por _______.',
'¿Qué es el mejor amigo de una chica?',
'Los estudios demuestran que las ratas de laboratorio resuelven laberintos un 50% más rápido tras ser expuestas a _____.',
'¿Qué me han estado ocultando mis padres?'
];
/*'2. Así es yo maté a ____, ¿Que cómo lo hice? _____.',
'2. Y el premio de la academia por _________ es para ____.',
'2. En mi próximo truco sacaré ______ de _______.',
'2. Canal Historia presenta: _______ la historia de __________.',
'2. ¿Cual es la próxima pareja de superhéroes?',
'2. Mientras flipaba con acido ____ se convirtio en ____.',
'3. Haz un haiku.'*/