exports.list = [
'Barack Obama.',
'Kebabs.',
'Esperanza Aguirre.',
'Correrse en una piscina llena de lágrimas de niño.',
'Un sombrero muy guay.',
'Auschwitz.',
'Tirarse un pedo e irse.',
'Un pelo púbico desviado.',
'Pelotas.',
'Ritos de apareamiento.',
'Olos a viejos.',
'Un terrorista gracioso.',
'Fuego amigo.',
'Frigo pie.',
'Keanu Reeves en Matrix.',
'Carne de vaca loca.',
'Christopher Nolan.',
'Leticia Sabater.',
'Carmen de Mairena.',
'El huracán Katrina.',
'Racismo.',
'Travestis que dan el pego.',
'Tocamientos genitales.',
'El 11-M.',
'Esperar hasta el matrimonio.',
'El clítoris.',
'Tíos que no vuelven a llamar.',
'Toma dos tazas.',
'Una tortuga mordiendo la punta de tu pene.',
'Pedófilos.',
'Bono de U2.',
'Michael Jackson.',
'Jack Skeletor.',
'La canción del Tiburón.',
'Impotencia.',
'Natarlie Portman.',
'El Big Bang.',
'Bromas sobre el Holocausto en un momento inoportuno.',
'Chupar un pirulo.',
'Gansos.',
'¿Abejas?',
'Los judíos.',
'Los gays.',
'SIDA.',
'Monaguillos.',
'La tuna.',
'Sobrecompensación.',
'Esas veces en las que te entra arena en la vagina.',
'Gary Coleman.',
'Una fiesta de cumpleaños decepcionante.',
'Intercambiar saludos.',
'Su alteza Real, la Reina Isabel II.',
'Menstruación.',
'Tener un gatillazo en los preeliminares.',
'El teletubby gay.',
'Propaganda homosexual.',
'Practicar un aborto usando una percha.',
'La Sagrada Biblia.',
'Cienciología.',
'Tom Cruise.',
'Todas las gambas que puedas comer por 4.99€.',
'Despertarse medio desnudo en el parking del McDonalds.',
'Ana Rosa Quintana.',
'Ataques de dinosaurios.',
'Protector dental.',
'Condones de sabores.',
'Abstinencia.',
'Nazis.',
'América.',
'Calentamiento global.',
'Ciencia.',
'Chupa Chups.',
'Un aumento de pechos asimétrico.',
'Hacerlo por el culo.',
'Andar como un retrasado.',
'Pezones empitonados.',
'Desodorante Axe. ',
'Paris Hilton.',
'Hara-kiri.',
'Bond, James Bond.',
'Lamer algo y luego decir que es tuyo.',
'Comer hasta vomitar.',
'Autocanibalismo.',
'Piercing genitales.',
'Esa cosa que electrocuta tus abdominales.',
'Cagar en la sopa.',
'Comportarse como un gilipollas con los niños.',
'Pedofilia.',
'Alcoholismo.',
'Un feto.',
'Que entren a robar en tu casa y que violes a los ladrones.',
'Levadura.',
'Curar la homosexualidad con la oración.',
'Superman.',
'Pubertad.',
'200 gramos de heroína mexicana.',
'Agricultura.',
'Dinámicas de grupo.',
'El conejo de Nesquick.',
'Trolls.',
'Un mar de problemas.',
'Obesidad.',
'Tinder.',
'Caballerosidad.',
'Un halcón con una gorra en la cabeza.',
'Fabada Litoral.',
'Eduard Punset.',
'¡¡¡BATMAN!!!',
'El café más caro del Starbucks.',
'Una ensalada de Telepizza.',
'Estar en la cama.',
'Amigos que se comen hasta tu hígado.',
'Gente negra.',
'Niños y petas.',
'Frank de la Jungla.',
'El KKK.',
'Preguntas de selectividad basadas en la raza.',
'Polvorones.',
'Bukkake pixelado.',
'Lluvias doradas.',
'Comerse la Nocilla a cucharadas.',
'Isabel Pantoja.',
'El golpe de Estado del 23 de febrero.',
'Gandhi.',
'Un curandero.',
'Hacer pucheritos.',
'Limpieza étnica.',
'Phoskitos.',
'Mi colección de juguetes sexuales de alta tecnología.',
'Huevos de pterodáctilo.',
'Jose Luis Rodriguez Zapatero.',
'Will Smith.',
'Dr. Martin Luther King, Jr.',
'Esclavitud.',
'Sex bomb.',
'Fantasmas.',
'Selección natural.',
'Espinete.',
'Sufragio femenino.',
'Diseño inteligente.',
'Selección natural.',
'Levantar el cuello de la camisa.',
'Las vías del metro.',
'Necrofilia.',
'Torsión testicular.',
'Lactancia.',
'Dulce, dulce venganza.',
'Minas terrestres.',
'Cabras comiendo latas.',
'Los discapacitados profundos.',
'Profesores sustitutos.',
'Los gitanos.',
'Elmo cosquillas.',
'Esta respuesta es post-moderna.',
'Dos enanos cagando en un cubo.',
'Mi alma.',
'Mis genitales.',
'Hacerlo con otra persona delante de tu novia.',
'Pasivo-agresividad.',
'Snoop Dogg.',
'Transporte de fluidos.',
'Combustión humana espontánea.',
'La marcha atrás.',
'Otra maldita película de vampiros.',
'El perro de Chocapic.',
'Justin Bieber.',
'Tiempo para uno mismo.',
'Incesto.',
'Heath Ledger en Batman.',
'Tensión sexual.',
'La sangre de Cristo.',
'Mahoma.',
'Emociones.',
'Viagra.',
'Ser rico.',
'Fantasías con leñadores.',
'Padres muertos.',
'Chupar algunas pollas para no ser reclutado.',
'Una pistola de agua llena de meado de gato.',
'Poluciones nocturnas.',
'Ser fabuloso.',
'Arnold Schwarzenegger.',
'Esbozar una sonrisa ante la mención de Camboya.',
'Motosierras en vez de manos.',
'Darth Vader.',
'Bob Esponja.',
'Atún en lata con extra de delfín.',
'Vikingos.',
'El corazón de un niño.',
'Lepra.',
'Britney Spears a los 55.',
'Un buen salchichón.',
'Asiáticos que no son muy buenos en mates.',
'Una gran expectativa sobre nada.',
'Una rascada clandestina de culo.',
'Polvo de ángel.',
'Decirlo adiós a Dios.',
'Un agujero del culo blanqueado.',
'La placenta.',
'Yo nunca.',
'Familias gitanas.',
'Cartas contra la humanidad.',
'Empollones.',
'Destrucción mutua asegurada.',
'Miedo a los desconocidos.',
'Un bocata de albóndigas.',
'Idiotas con sus iPhones.',
'Declaración de los Derechos Humanos.',
'Preadolescentes.',
'Existencialistas.',
'Baltasar Garzón.',
'Esmegma.',
'Morir de disentería.',
'Los niños de la guerra.',
'El Papa.',
'William Shapeskeare.',
'Envidia de pene.',
'Complejo de Edipo.',
'Soy amigo de tu padre en Facebook.',
'Complejo de Elecktra.',
'Una tortura china.',
'Mi vida sexual.',
'Oompas Loompas.',
'Un giro de guión de M. Night Shyamalan.',
'Tercera base.',
'Dejar un mensaje de voz incómodo.',
'Hacerse un dedo.',
'José María Aznar.',
'Gente que huele sus propios calcetines.',
'Catapultas.',
'Semen de ballena.',
'Viuda Negra.',
'Los Pecos.',
'Comer sandía.',
'Un hombre de mediana edad en patines.',
'Artefactos explosivos caseros.',
'Estrógeno.',
'Una mujer negra descarada.',
'Peleas de pollos.',
'Manazas.',
'Lesbianas nazis borrachas que dan palizas.',
'(Estoy haciendo ejercicios vaginales ahora mismo.)',
'Porno alemán sadomasoquista.',
'Gloryholes.',
'¡Cachorritos!',
'Una paja triste.',
'Felación al volante.',
'La abuelita.',
'Tener la mandíbula inmobilizada.',
'Un micropene.',
'Sentir miedo de ti mismo.',
'Pájaros que no pueden volar.',
'Ropa interior comestible.',
'Un mal entendido guarrete.',
'Herpes labial.',
'La trama de una película de Michael Bay.',
'Abdominales espectaculares.',
'El calvo de la loteria.',
'Sexo con señoras gordas.',
'Robert Downey, Jr.',
'Ir a una orgía sólo por la comida.',
'Zorritas.',
'Una explosión termonuclear.',
'Un molino lleno de cadáveres.',
'El Santiago Bernabeu.',
'Pezones que se escapan del vestido.',
'Música New Age.',
'Solos de saxofón.',
'Masturbación.',
'Prepucio.',
'Quitarte la camiseta.',
'Tamborileros.',
'Seducción.',
'Gente pobre.',
'Gente sin hogar.',
'Arco iris y rayos de sol.',
'Una lan party.',
'Follamigos.',
'Gancho de izquierda.',
'Limpiarte el culo.',
'Krusty el Payaso.',
'Muestras gratuitas.',
'Gladiadores americanos.',
'Mear una piedra del riñón.',
'Accidentes de caza.',
'Enfermedad de las vacas locas.',
'Bolsitas de té.',
'Ciudadanos sin culo.',
'El sur.',
'Meterse una buena raya.',
'Echar un vistazo.',
'Piruletas enormes.',
'Heineken.',
'Federico Jiménez Losantos.',
'Un canalillo generoso.',
'Bolsas de patatas fritas con aun mas aire.',
'Aguafiestas.',
'Música turbo-folk de Europa del Este.',
'Cagarse encima.',
'Viejos japoneses.',
'Gente blanca.',
'Una erección que dura más de 4 horas.',
'Pavonearse.',
'Porno con tentáculos.',
'El perineo.',
'El Cascanueces.',
'Barriga en forma de culo.',
'"Twitteando".',
'Miembros amputados.',
'Patinaje artístico sobre hielo con personas del mismo sexo.',
'El equipo de gimnasia chino.',
'Labios vaginales enormes.',
'Una vida de tristeza.',
'Asaltar tumbas.',
'Ponerse la ropa interior al revés para no tener que lavarla.',
'Síndrome del colon irritable.',
'La paz mundial.',
'Centauros.',
'Bajas civiles.',
'La Macarena.',
'La carrera de actor de Shaquille O\'Neal.',
'Judíos con el pelo a lo afro.',
'Gente cachonda.',
'El testículo perdido de Lance Armstrong.',
'Stephen Hawking diciendo guarradas.',
'Chicas que no deberían desmadrarse.',
'Italianos.',
'Mi relación de pareja.',
'Pilotos kamikazes.',
'Arcadas.',
'Represión.',
'Cortar cabelleras.',
'Trabajar como un chino.',
'Francisco Franco.',
'2 Girls 1 Cup.',
'Bolas chinas.',
'Concursos de belleza infantil.',
'Se ha escrito un crimen.',
'Fricción.',
'Violar a un conocido.',
'¡¡¡SEXO SORPRESA!!!',
'Lanzamiento de enanos.',
'Una lobotomía hecha con un picahielos.',
'La vagina de Pilar Bardem.',
'Niños con correas.',
'Actitud.',
'Un camello de dibujos animados disfrutando el fresco sabor de un cigarrillo.',
'Acurrucarse con tu pareja.',
'Múltiples heridas por apuñalamiento.',
'Emborracharse con enjuage bucal.',
'Esnifar pegamento.',
'¡JHON CENA!.',
'El gay que aparece en todas las series modernas.',
'Constantino Romeo durmiendo en un colchón LoMonaco.',
'Bestialidad.',
'Colegios tradicionalmente negros.',
'Beber solo.',
'Niños con cáncer de culo.',
'Cagar y bautizarlo.',
'Mujeres en anuncio de yogurt.',
'Manos de pianista.',
'Comida para gatos.',
'Un sorteo de bofetadas.',
'Hacer lo correcto.',
'World of Warcraft.',
'Desayunar con la reina.',
'Ocultar una erección.',
'Mearse un poquito.',
'Cuando te tiras un pedo y te cagar un poquito.',
'Hacer trampas en las Olimpiadas Especiales.',
'La estupidez del ser humano.',
'Desayunar un burrito con olor a culo.',
'Pedos vaginales.',
'Dar el 110%.',
'Robarle la novia a otro.',
'Enseñarle a un robot a amar.',
'Re-regalar.',
'Atracar un banco de esperma.',
'Alimentar a Montserrat Caballé.',
'Darse por culo debajo de las sábanas.',
'Un Tamagotchi abandonado.',
'Un mongolo musculado.',
'Morir.',
'Comerse las galletas antes de la venta benéfica.',
'Comer directamente de la olla.',
'Hacer un reloj de arena.',
'Sexo oral no recíproco.',
'Guiñarle el ojo a los viejos.',
'Ligar en la clínica de aborción.',
'Cabrearte tanto que te empalmas.',
'Escuchar atentamente.',
'Bebés muertos.',
'Una carrera de sillas de ruedas hasta la muerte.',
'Un mono fumando un cigarrillo.',
'Demasiada gomina.',
'Un mimo teniendo un ataque al corazón',
'Pacman comiendo corrida descontroládamente.',
'Un relato erótica de Harry Potter.',
'Peanut Butter Jelly Time.',
'Kim Jong-il.',
'Ladillas.',
'Vaginas en lata.',
'Zoofilia.',
'Necrofilia.',
'Mariano Rajoy.'
];